import { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import api, { fd, P, money } from '../api';
import { useGet, Offline, Magnetic, Parallax, Reveal, Skeleton, SpotlightCard } from '../components';

const STEPS = [['01', 'Choose your ritual', 'Explore considered hair, colour, skin and spa services with transparent pricing.'], ['02', 'Meet your match', 'Choose the specialist you want, then see only the times they can actually welcome you.'], ['03', 'Make it yours', 'Book in a few taps. Reschedule, cancel, or revisit your appointment history whenever you need.']];
const WHY = [['Real availability', 'No back-and-forth calls. Our calendar reflects each stylist’s hours and current bookings.'], ['A quieter kind of luxury', 'Thoughtful service, clear prices and time held just for you.'], ['Your visit, your way', 'Change plans from your account without having to explain yourself twice.'], ['People who care', 'A small team of specialists who listen before they reach for the scissors.']];
const QUOTES = [['“The whole experience feels calm, personal and beautifully considered. Riya understood exactly what I wanted.”', 'Ananya S.'], ['“I moved my colour appointment twice without calling anyone. That alone is worth it.”', 'Kunal M.'], ['“The hair spa was the best hour of my week. I book it every month now.”', 'Isha P.']];

function NextSlots() {
  const [s, setS] = useState(null);
  useEffect(() => { let active = true; api.get('/availability/next').then((r) => active && setS(r.data || false)).catch(() => active && setS(false)); return () => { active = false; }; }, []);
  return <div className="card nextcard"><div className="eyebrow">Live availability</div><h3>Find a moment for yourself.</h3>{s === null && <p className="hint" style={{ marginTop: 14 }}>Checking today’s calendar…</p>}{s === false && <p className="hint" style={{ marginTop: 14 }}>Choose a ritual and we’ll show you the next times your preferred specialist can welcome you.</p>}{s && <><p className="hint" style={{ margin: '14px 0 16px' }}>{s.service.name} with {s.staff.name}<br />{fd(s.date)}</p><div className="chips">{s.slots.map((x) => <Link key={x.start} className="chip" to={`/book?service=${s.service._id}&staff=${s.staff._id}&date=${s.date}&time=${x.start}`}>{P(x.start)}</Link>)}</div></>}<Link to="/reserve" className="btn" style={{ marginTop: 22 }}>Explore availability</Link></div>;
}

export default function Home() {
  const { data: svcs, err } = useGet('/services'), { data: staff } = useGet('/staff');
  return <>
    <section className="wrap hero"><div><div className="eyebrow motion-eyebrow">Aurel Salon Studio · Ahmedabad</div><h1 className="hero-title"><span>Beauty,</span> <em>considered.</em></h1><p className="hero-copy">A slower, more personal salon experience for hair, colour, skin and the rituals that make a day feel like yours again.</p><div className="hero-actions"><Magnetic><Link to="/reserve" className="btn">Reserve a visit</Link></Magnetic><Magnetic><Link to="/services" className="btn g">Explore the menu</Link></Magnetic></div><div className="facts"><div><b>{staff ? staff.length : 3}</b>specialists</div><div><b>{svcs ? svcs.length : 10}</b>rituals</div><div><b>10–19</b>six days a week</div></div></div><Parallax className="hero-art" strength={.12}><figure className="hero-photo"><img src="/aurel-salon-hero.jpg" alt="Warmly lit luxury salon interior with a sculptural styling chair" loading="eager" fetchPriority="high" decoding="async" /><figcaption><span>AUREL / 01</span><span>THE STUDIO</span></figcaption></figure></Parallax></section>
    <div className="marquee" aria-label="Aurel services"><div className="marquee-track"><span className="marquee-segment">HAIR <i>✦</i> COLOUR <i>✦</i> SKIN <i>✦</i> SPA <i>✦</i></span><span className="marquee-segment" aria-hidden="true">HAIR <i>✦</i> COLOUR <i>✦</i> SKIN <i>✦</i> SPA <i>✦</i></span><span className="marquee-segment" aria-hidden="true">HAIR <i>✦</i> COLOUR <i>✦</i> SKIN <i>✦</i> SPA <i>✦</i></span><span className="marquee-segment" aria-hidden="true">HAIR <i>✦</i> COLOUR <i>✦</i> SKIN <i>✦</i> SPA <i>✦</i></span></div></div>
    <section className="band alt"><div className="wrap"><div className="section-head"><div><div className="eyebrow">The menu</div><h2>Small rituals.<br />Beautiful results.</h2></div><p>From precision cuts to restorative colour and skin treatments, every service is designed around your time and your style.</p></div>{err && <Offline />}<div className="grid">{svcs ? svcs.slice(0, 3).map((s, i) => <Reveal key={s._id} delay={i * 90}><SpotlightCard className="card svc"><div className="eyebrow">{String(i + 1).padStart(2, '0')} / {s.duration} min</div><h3>{s.name}</h3><p>{s.description}</p><div className="price">{money(s.price)}</div><Link to={`/reserve?service=${s._id}`} className="text-link">Begin this ritual <span>↗</span></Link></SpotlightCard></Reveal>) : <><Skeleton className="dark-skeleton" /><Skeleton className="dark-skeleton" /><Skeleton className="dark-skeleton" /></>}</div><div className="catalog-cta"><Magnetic><Link to="/services" className="btn g">View the full menu <span aria-hidden="true">↗</span></Link></Magnetic><span className="catalog-count">10 rituals to explore</span></div></div></section>
    <section className="band availability-band"><div className="wrap two"><div><div className="eyebrow">Your time, made visible</div><h2>See the next<br />open moment.</h2><p className="hint big">We calculate availability from each specialist’s working hours and current appointments, so the first time you see is a real one.</p></div><NextSlots /></div></section>
    <section className="band"><div className="wrap"><div className="section-head"><div><div className="eyebrow">The Aurel way</div><h2>Booking, without<br />the friction.</h2></div><p>Everything you need for a beautifully simple appointment, in one place.</p></div><div className="grid">{STEPS.map(([n, t, d]) => <Reveal key={t}><div className="card"><div className="num">{n}</div><h3>{t}</h3><p className="hint" style={{ marginTop: 12 }}>{d}</p></div></Reveal>)}</div></div></section>
    <section className="band alt"><div className="wrap"><div className="section-head"><div><div className="eyebrow">The people</div><h2>Good hands,<br />good energy.</h2></div><p>Meet the specialists who make Aurel feel less like an errand and more like a reset.</p></div><div className="grid">{staff ? staff.map((t) => <Link key={t._id} to="/team" className="card staffc"><div className="av">{t.name[0]}</div><div><h3>{t.name}</h3><p className="hint">{t.role}</p></div></Link>) : <><Skeleton className="dark-skeleton" /><Skeleton className="dark-skeleton" /></>}</div></div></section>
    <section className="band"><div className="wrap"><div className="section-head"><div><div className="eyebrow">Why Aurel</div><h2>Luxury is<br />how it feels.</h2></div></div><div className="grid why">{WHY.map(([t, d]) => <div key={t}><h3>{t}</h3><p className="hint" style={{ marginTop: 10 }}>{d}</p></div>)}</div></div></section>
    <section className="band alt"><div className="wrap"><div className="section-head"><div><div className="eyebrow">Client notes</div><h2>Kind words.</h2></div></div><div className="grid">{QUOTES.map(([q, n]) => <figure className="card quote" key={n}><blockquote>{q}</blockquote><figcaption>{n}</figcaption></figure>)}</div></div></section>
    <section className="wrap cta"><div className="eyebrow">Your next ritual</div><h2>Make a little room<br />for yourself.</h2><p className="hint big">Choose a service, meet your stylist and let us take it from there.</p><Link to="/reserve" className="btn">Reserve a visit</Link></section>
  </>;
}
